### ISSUE TITLE
Typos - "started" and "opening"

### ISSUE THREAD

**Issue by technomaz** [Sitefinity/Sitefinity-CLI#85] opened 2020-10-12 20:09 UTC
The word "started" is misspelled:
https://github.com/Sitefinity/Sitefinity-CLI/blob/4d313696ae4aa9c5b30e853a13ec288d28ed5632/Sitefinity%20CLI/PackageManagement/SitefinityPackageManager.cs#L52

The word "opening" is misspelled:
https://github.com/Sitefinity/Sitefinity-CLI/blob/4d313696ae4aa9c5b30e853a13ec288d28ed5632/Sitefinity%20CLI/PackageManagement/VisualStudioWorker.cs#L45

**Comment by RuzmanovDev** [comment] 2020-12-02 09:37
Thanks for the feedback. We will adress it with next versions of the cli

**Comment by sevastoyanova** [comment] 2021-03-11 14:28
The issue is fixed in https://github.com/Sitefinity/Sitefinity-CLI/releases/tag/v1.1.0.19

**Closed by sevastoyanova** 2021-03-11 14:28 UTC
