### ISSUE TITLE
Execution policy blocks running of updater.ps1 file

### ISSUE THREAD

**Issue by JoshuaDouce** [Sitefinity/Sitefinity-CLI#67] opened 2020-07-30 12:25 UTC
In order to get the updater to run I had to run this command first

Unblock-File -Path '.\PowerShell\Updater.ps1'

**Comment by RuzmanovDev** [comment] 2020-12-02 09:38
Thanks for the feedback, We will add it to our backlog. Expect fix in future versions of the CLI

**Comment by azavarben** [comment] 2021-01-19 22:16
Same issue.

**Comment by RuzmanovDev** [comment] 2021-02-16 15:54
The issue is fixed in https://github.com/Sitefinity/Sitefinity-CLI/releases/tag/v1.1.0.18

**Closed by RuzmanovDev** 2021-02-16 15:54 UTC
